application: facebook-javascript-api
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /xfbml.html
  static_files: xfbml.html
  upload: xfbml.html

- url: /html5.html
  static_files: html5.html
  upload: html5.html

- url: /.*
  static_files: index.html
  upload: index.html
